version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      storybook:
        patterns:
          - "storybook"
          - "@storybook/*"
      turf:
        patterns:
          - "@turf/*"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
    commit-message:
      prefix: "dependency:"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "actions:"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
