name: Publish @osrd-project on Release

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Authenticate with Registry
        run: |
          echo "registry=https://registry.npmjs.org/" > ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN > ~/.npmrc"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 'Build & deploy'
        run: |
          npm ci
          npm run build
          lerna publish from-package --no-private --yes
